function FilesRelocationPairsRep()

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%PART I: copy ENCODING files
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%variables and folder

DirName='C:\fMRI_Data\SEL2\ANALYSIS_SPM8\';% Root location of analysis folder


subs= {...
    '200615TF';...
     '230615ZD';...
     '230615EF';...
     '230615RE';...
     '270615SA';...
     '270615NK';...
     '270615RP';...
     '110715DA';...
     '110715YB';...
     '110715YL';...
       '240715TP';...
       '250715LK';...
       '250715AG';...
       '250715EB';...
       '080815EF';...
       '080815LR';...
       '080815RM';...
       '080815TN';...
       '110815EZ';...
    }; 

condnm = {... % array of all contrasts names; this is the way they will appear in the results menu;
'FamousAndNonFamousAll',...
'Famous',...
'Nonfamous',...
'Famous_Nonfamous',...
'Nonfamous_Famous',...
'Famous1',...
'NonFamous1',...
'Famous123',...
'NonFamous123',...
'FamousLinDecrease',...
'NonFamousLinDecrease',...
'FamousExpDecreaseNatlog',...
'NonFamousExpDecreaseNatlog',...
'FamousExpDecrease2PowerRep',...
'NonFamousExpDecrease2PowerRep',...
'FandNF',...
'FminusNF',...
'F123andNF123',...
'F123minusNF123',...
'FlinAndNFlin',...
'FlinMinusNFlin',...
};
%fnames=fieldnames(names);

resdir= 'results_pairsRep_smt_norm_msessions';
destdir='GROUP_pairs_RepModel';
% nconts=length(condnm);
ignoreconts=39; %number of contrust that will not be removed to the group directory (such as the initial conditions).
destin_dir = fullfile(DirName,destdir);
nconts=ignoreconts+length(condnm);

for i=ignoreconts+1:nconts

for j=1:length(subs)
    patient=char(subs(j));
	
    if i <10

        FileSource1=fullfile(DirName, sprintf('%s', patient), sprintf('%s',resdir), sprintf('con_000%d.hdr',i));
        FileSource2=fullfile(DirName, sprintf('%s', patient), sprintf('%s',resdir), sprintf('con_000%d.img',i));

        ContrastFolder = fullfile(DirName, destdir, condnm{i-ignoreconts});

            if ~exist(ContrastFolder)
            mkdir (ContrastFolder);
            mkdir (fullfile(ContrastFolder,'subs_con_files'));
            end

        FileDestination1=fullfile(ContrastFolder, 'subs_con_files', sprintf('con_00%d_%s_%s.hdr',i, patient,resdir));
        FileDestination2=fullfile(ContrastFolder, 'subs_con_files',  sprintf('con_00%d_%s_%s.img',i, patient,resdir));


        eval(['!copy ' FileSource1 ' ' FileDestination1]);
        eval(['!copy ' FileSource2 ' ' FileDestination2]);

    else

        FileSource1=fullfile(DirName, sprintf('%s', patient), sprintf('%s',resdir), sprintf('con_00%d.hdr',i));
        FileSource2=fullfile(DirName, sprintf('%s', patient), sprintf('%s',resdir), sprintf('con_00%d.img',i));

        ContrastFolder = fullfile(DirName, destdir, condnm{i-ignoreconts});

            if ~exist(ContrastFolder)
            mkdir (ContrastFolder);
            mkdir (fullfile(ContrastFolder,'subs_con_files'));
            end

        FileDestination1=fullfile(ContrastFolder, 'subs_con_files', sprintf('con_00%d_%s_%s.hdr',i, patient,resdir));
        FileDestination2=fullfile(ContrastFolder, 'subs_con_files', sprintf('con_00%d_%s_%s.img',i, patient,resdir));

        eval(['!copy ' FileSource1 ' ' FileDestination1]);
        eval(['!copy ' FileSource2 ' ' FileDestination2]);
    end;

end
end

clear all
